namespace:
  name: library-app

global:
  appName: library-management-system

mysql:
  name: mysql
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent

  service:
    name: mysql-service
    headlessName: mysql-headless
    port: 3306

  auth:
    rootPassword: "rifkhansaa"
    database: "library_db"
    username: "appuser"
    password: "rifkhansaa"

  storage:
    size: 1Gi

  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

backend:
  name: backend
  replicas: 2

  image:
    repository: rifkhan6526/library-backend
    tag: v1
    pullPolicy: IfNotPresent

  service:
    name: backend-service
    type: ClusterIP
    port: 5000
    targetPort: 5000

  config:
    port: "5000"
    dbHost: mysql-service
    dbPort: "3306"
    dbName: library_db
    dbUser: appuser
    jwtExpiresIn: "1d"

  secret:
    dbPassword: "rifkhansaa"
    jwtSecret: "library-super-secret-jwt-key-2026"

  probes:
    enabled: true
    startup:   # startupProbe checks whether backend started
      path: /api/live
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 12

    readiness: # readinessProbe checks whether backend can serve traffic and connect to MySQL
      path: /api/ready
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 3

    liveness: # livenessProbe checks whether backend process is alive
      path: /api/live
      initialDelaySeconds: 30
      periodSeconds: 20
      failureThreshold: 3

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

frontend:
  name: frontend
  replicas: 2

  image:
    repository: rifkhan6526/library-frontend
    tag: v1
    pullPolicy: IfNotPresent

  service:
    name: frontend-service
    type: ClusterIP
    port: 80
    targetPort: 80

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

ingress:
  enabled: true
  name: library-ingress
  className: nginx
  host: library.local