namespace:
  name: library-dev

backend:
  image:
    repository: rifkhan6526/library-backend
    tag: latest
    pullPolicy: Always

frontend:
  image:
    repository: rifkhan6526/library-frontend
    tag: latest
    pullPolicy: Always

mysql:
  storage:
    size: 1Gi

ingress:
  host: library-dev.local