apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.headlessName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.mysql.name }}

spec:
  clusterIP: None

  selector:
    app: {{ .Values.mysql.name }}

  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.mysql.name }}

spec:
  type: ClusterIP

  selector:
    app: {{ .Values.mysql.name }}

  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.mysql.name }}
    app.kubernetes.io/component: mysql

spec:
  serviceName: {{ .Values.mysql.service.headlessName }}
  replicas: 1

  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
        app.kubernetes.io/component: mysql

    spec:
      containers:
        - name: {{ .Values.mysql.name }}
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}

          ports:
            - name: mysql
              containerPort: {{ .Values.mysql.service.port }}

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql

          resources:
{{ toYaml .Values.mysql.resources | indent 12 }}

  volumeClaimTemplates:
    - metadata:
        name: mysql-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: {{ .Values.mysql.storage.size }}